openapi: 3.0.0
info:
  title: blockchain_go API
  version: 1.0.0
paths:
  /signup:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: token
  /login:
    post:
      summary: Login and receive JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: token
  /order:
    post:
      summary: Create new order
      responses:
        '200':
          description: created order
  /order/{id}/roles:
    post:
      summary: Assign role to actor
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
  /order/{id}/status:
    post:
      summary: Update order status
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
  /order/{id}/invite:
    post:
      summary: Invite watcher
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
  /order/{id}/events:
    get:
      summary: Get order events
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: events
  /chain:
    get:
      summary: Retrieve full chain
      responses:
        '200':
          description: chain
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        first_name:
          type: string
        last_name:
          type: string
